### ISSUE TITLE
what does 'peer distillation' mean? how does it work?

### ISSUE THREAD

**Issue by a26z15** [ygtxr1997/MSML#6]
Hello,

Thanks for sharing the codes! I don't understand the function of 'peer distillation' in the codes. And how does it work? Thanks a lot!

**Comment by ygtxr1997** [comment]
'peer distillation' is an experimental setting in the codes. You can ignore or delete the codes that are related to 'peer distillation'.

**Comment by a26z15** [comment]
Is it used during training? By the way, what's the function of 'decoder' and the meaning of 'ori' in the codes? Thanks for answering!

**Comment by ygtxr1997** [comment]
'decoder', 'ori', and 'peer distillation' are all useless.
'decoder' and 'ori' are also used for 'peer distillation'.
They're not used for MSML training.

**Comment by ygtxr1997** [comment]
You can set 'config.yaml' as follows to fully shut down the 'peer distillation':
```yaml
peer_params:
  use_ori: false  # for fm and frb
  use_conv: true  # for fm
  mask_trans: 'conv'  # 'conv', 'invert', for fm
  use_decoder: false  # for frb
```
